# Generated by Django 2.1.3 on 2018-11-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20181114_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='CSVFile',
        ),
    ]
